### ISSUE TITLE
Is there an error with dataset generation and filtering?

### ISSUE THREAD

**Issue by xubin15** [OpenPerceptionX/TCP#19]
Hello,
I try to generate datasets and filter them. There is no meta folder in the dataset generated using **data_collection.sh**. But filtering with **filter_data.py** requires a meta folder.  
In **filter_data.py**
![2022-12-07 20-28-23屏幕截图](https://user-images.githubusercontent.com/74893013/206183259-7ac65050-2bac-4926-a3b2-cdb7e73d59c0.png)
Folders generated by **data_collection.sh**
![2022-12-07 20-51-02屏幕截图](https://user-images.githubusercontent.com/74893013/206184007-baf45d54-b9d1-4f9e-b57c-91065043ad0c.png)

**Comment by WPH-commit** [comment]
I think the "meta" should be changed to measurements. Sorry for this problem.

**Comment by xubin15** [comment]
Thank you
