### ISSUE TITLE
Town07 and Town10 scenarios containing Town02 scenarios

### ISSUE THREAD

**Issue by ishida-wayve** [OpenPerceptionX/TCP#32]
Hello! I noticed that the [Town07 scenarios](https://github.com/OpenPerceptionX/TCP/blob/main/leaderboard/data/scenarios/town07_all_scenarios.json) and [Town10 scenarios](https://github.com/OpenPerceptionX/TCP/blob/main/leaderboard/data/scenarios/town10_all_scenarios.json) actually contain town02 scenarios. Could you update this with the correct scenarios please? 
Could you also point me to how these scenarios were generated and how I can generate my own scenarios please? Thank you!

**Comment by WPH-commit** [comment]
We use the scenario files from the Transfuser repo, please refer to this issue https://github.com/autonomousvision/transfuser/issues/59

**Comment by ishida-wayve** [comment]
I see! Thanks for the clarification!
